-- local default_avante_provider = "ollama" -- Fallback
--
-- -- Check an environment variable to set the default provider
-- if vim.env.NVIM_AVANTE_PROFILE == "work" then
--   default_avante_provider = "work_claude" -- Or whatever you defined for work
-- elseif vim.env.NVIM_AVANTE_PROFILE == "personal" then
--   default_avante_provider = "ollama"      -- Or another personal default
-- end
--
-- return {
--   "yetone/avante.nvim",
--   build = function()
--     if vim.fn.has("win32") == 1 then
--       return "powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false"
--     else
--       return "make"
--     end
--   end,
--   event = "VeryLazy",
--   version = false,
--   ---@module 'avante'
--   ---@type avante.Config
--   opts = {
--     system_prompt = function()
--       local hub = require("mcphub").get_hub_instance()
--       return hub and hub:get_active_servers_prompt() or ""
--     end,
--     -- Using function prevents requiring mcphub before it's loaded
--     custom_tools = function()
--       return {
--         require("mcphub.extensions.avante").mcp_tool(),
--       }
--     end,
--     -- Define the default provider
--     provider = default_avante_provider,
--     -- Define all available providers
--     providers = {
--       work_claude = {
--         endpoint = "https://api.anthropic.com",
--         model = "claude-sonnet-4-20250514",
--         timeout = 30000,
--         extra_request_body = {
--           temperature = 0.75,
--           max_tokens = 20480,
--         },
--       },
--       ollama = {
--         endpoint = "http://localhost:11434",
--         model = "llama3.2:latest",
--         -- extra_request_body = {
--         --   temperature = 0.3,  -- Lower for more focused responses
--         --   num_predict = 2048, -- Limit response length
--         --   top_p = 0.9,        -- More focused sampling
--         -- },
--       },
--     },
--   },
--   dependencies = {
--     "nvim-lua/plenary.nvim",
--     "MunifTanjim/nui.nvim",
--     "echasnovski/mini.pick",
--     "nvim-telescope/telescope.nvim",
--     "hrsh7th/nvim-cmp",
--     "ibhagwan/fzf-lua",
--     "stevearc/dressing.nvim",
--     "folke/snacks.nvim",
--     "nvim-tree/nvim-web-devicons",
--     "zbirenbaum/copilot.lua",
--     {
--       "HakonHarnes/img-clip.nvim",
--       event = "VeryLazy",
--       opts = {
--         default = {
--           embed_image_as_base64 = false,
--           prompt_for_file_name = false,
--           drag_and_drop = {
--             insert_mode = true,
--           },
--           use_absolute_path = true,
--         },
--       },
--     },
--     {
--       "MeanderingProgrammer/render-markdown.nvim",
--       opts = {
--         file_types = { "markdown", "Avante" },
--       },
--       ft = { "markdown", "Avante" },
--     },
--   },
-- }
return {}
